version: '3.8'

services:
  snmp-viewer:
    build: .
    container_name: snmp-viewer
    ports:
      - "3000:3000"
    volumes:
      - ./mibs:/usr/src/app/mibs
      - ./public:/usr/src/app/public
      - ./server.js:/usr/src/app/server.js
    restart: unless-stopped
